### ISSUE TITLE
--controller argument to generate_supervisor

### ISSUE THREAD

**Issue by o7n** [vespene-io/vespene#10]
`6_services.sh` calls 

`$PYTHON manage.py generate_supervisor --controller --path /etc/vespene/supervisord.conf --workers "$WORKER_CONFIG" --executable=$PYTHON`

which yields
`manage.py generate_supervisor: error: unrecognized arguments: --controller`

and indeed https://github.com/vespene-io/vespene/blob/master/vespene/management/commands/generate_supervisor.py does not seem to support an argument named `--controller` ?

**Comment by mpdehaan** [comment]
Yep, exactly, this was removed in some fileserver changes and I neglected to update the setup scripts. If you take out --controller it will work and I've already pushed the removal and am also retesting everything to verify.

Very sorry about that and thanks for the report!
