### ISSUE TITLE
Cannot login to Vespene forum using Github Account

### ISSUE THREAD

**Issue by kdbeall** [vespene-io/vespene#103]
When I try to login with my Github account on the forum the follow happens. I tried removing authorization for the forum in my Github account settings.
![screenshot from 2018-12-13 21-20-59](https://user-images.githubusercontent.com/10102694/49979444-07839b00-ff1d-11e8-9f7d-264e10f04aad.png)

**Comment by mpdehaan** [comment]
Ok, I tried to set up a new OAuth thing in GitHub but it just didn't work either.  So I've disabled GitHub logins for now, who knows what is wrong with discourse. Feel free to create an account with username + password.
