### ISSUE TITLE
0_common.sh script not properly detecting sudo

### ISSUE THREAD

**Issue by sgutermann** [vespene-io/vespene#106]
**Bug description**

Running the 0_common.sh script with sudo tells me to use sudo.

**Steps to reproduce**

Using a minimal debian run the script. Running "whoami" with sudo will return "root" so this is not a valid test.

**Expected behavior**

No error when run with sudo.

**Actual behavior**

Error saying to use sudo.

**Operating system and version**

Debian Stretch

**Any additional info**

Bare with me. Testing on Debain Stretch. Will try to do my first GitHub pull request. This is not funny.

**Comment by mpdehaan** [comment]
This is not a bug, the actual message is covered by this:

me=`whoami`
if [[ "$me" == "root" ]]; then
    echo "*** please re-run this script from a user account with sudo rights"
    exit 1
fi

You are not supposed to run the scripts with sudo, because the scripts themselves will invoke sudo --- not just to root, but also to the database user.

The alternative you might think would be to *ask* the scripts to be run with sudo (like you did), but the permissions from that get to be a bit too strong in some cases.

For instance on OS X, we want to run vespene as the user who ran the setup script.

Thus, the scripts should *not* be run with sudo, and they will sudo as needed.

**Comment by sgutermann** [comment]
Sorry to be picky about such a minor point. 

Messed up my pull request somehow as well (wrong git user). Please just kill that. Need to read the dummy instructions somewhere for that.

But my point still stands, testing whoami should then either be removed or the message needs to be clear.

If I am **not to run** the scripts with sudo then why tell me to "re-run this script from a user account with sudo rights".

The check in my pull request does nothing else other than tell the person he is using sudo or your message.

Am I missing something?

PS: Adding "#!/bin/bash" at the top would be nice, too.

**Comment by mpdehaan** [comment]
So, you would think maybe the message can be removed, but if I remove it, I'll get all the messages from people who run it without sudo.

I already got quite a few of those from people leaving it off.  This ensures I don't get the tickets from those folks.

So we *COULD* check and see if the user is already sudo'd (your change) and only raise that exit error on OS X... that should be fine as long as we don't hit any problems with the double sudoing (which I suspect we won't?)

How does that sound?

**Comment by sgutermann** [comment]
You can doubel and tripple sudo if you really feel like it. Try it. Do "sudo -i" which makes you root and then do "sudo -i" again. Now you are still root. Of course when you "exit" you are back to root and have to "exit" one more time.

I use this on a number of systems where Users have Access. Only thos that can sudo up to root are then allowed to sudo to postgres from there.

May not be the GOLDEN solution, but it works for me.

So I will do try once more. 

All you have to do is edit the messages to your liking. As in the "0_..." script this doesn't really do anything this might just be the point to be a bit more informative.

If you want to change it on the other scripts is up to you.

**Comment by sgutermann** [comment]
Ok, I finally got that with the pull request and signing the CLA figured out. So feel free to use it, trash it or change it.

As it is way late in germany I will get some sleep now. I am installing on an arm64 debian stretch. I saw the other debain issue but no one seems to have done a pull request. So if my install works I show up again and nag you.
