### ISSUE TITLE
default options for generate_supervisor.py

### ISSUE THREAD

**Issue by o7n** [vespene-io/vespene#11]
Disclaimer: I'm not really familiar with Django, so there might be something version related. 
This is on a clean CentOS 7.5 box.

An incorrect `supervisord.conf` was being generated - it turns out there is an issue with the default value of the omitted `source` parameter for `generate_supervisor.py`

This `source = options.get('source', '/opt/vespene/')` is not working - source becomes `None`

This does work:

```
parser.add_argument('--source', type=str, help='source', default='/opt/vespene/')
..
source = options.get('source')

```

Edit: (I see you just fixed this by adding the source= parameter while I was typing this message).

**Comment by mpdehaan** [comment]
Should be all fixed now, thanks again!.
