### ISSUE TITLE
Seem official website is down

### ISSUE THREAD

**Issue by shixinyu** [vespene-io/vespene#115]
http://vespene.io/ is unaccessabled and seem there's no any DNS records in this domain.

**Comment by sm4rk0** [comment]
It has been [discontinued](https://medium.com/@michaeldehaan/discontinuing-vespene-17fd9c0f3079).

**Comment by tnodesgithub** [comment]
bad news, so sad.

**Comment by shixinyu** [comment]
bad news, so sad.
