### ISSUE TITLE
use of ansible

### ISSUE THREAD

**Issue by jlozadad** [vespene-io/vespene#21]
hello,

Have you considered/though of using ansible instead of the shell scripts?

**Comment by MrOwen** [comment]
Likewise, would you be open the possibility of instead having a separate project under Vespene if you wanted to keep alternative setup methods available?

**Comment by mpdehaan** [comment]
I'm open to the seperate project, my initial thinking was that I didn't want to be in the business of keeping up with how to use ansible, as strange as that may sound, and more importantly - I don't want this to feel like this is a project that *requires* ansible knowledge or was for ansible (it's for everybody).

That being said, I did want to have playbooks originally, I just grew frustrated trying to figure out how to use it and stopped trying to write them.

The seperate project idea sounds like a really good idea to me.

There's also some discussion about docker going on at the moment, and similarly while I don't want to require docker we are going to have those in the main repo, and maybe a seperate repo for those orchestration/setup things too I think.

Can you stop by http://talk.vespene.io/ and post there?

I'm trying to keep this specific to pull requests and bug tickets, but don't really want to silence discussion - but that being said, the forum is a better place for that and I'm trying to get some volume going over there too :)

Thanks for the suggestion - this is a good idea.
