### ISSUE TITLE
Questionable choice of license

### ISSUE THREAD

**Issue by SirCmpwn** [vespene-io/vespene#22]
Hi, friendly neighborhood FOSS advocate here to complain about your license.

Please consider chosing a free and open source license. It'd be easy to use the Apache license, for example, by simply removing the Anti-Commons Clause from it. There are other licenses, like the AGPL, which may also serve your needs with respect to defending your work against profiteers. There are several practical problems with the Anti-Commons Clause:

- It's not possible to use this in any commercial environment because of the incredibly broad possible interpretations of "a product or service whose value derives from" your license.
- It's not possible to use this in an open source environment, because it doesn't uphold the essential freedoms of open source.

The Apache license is designed to provide rights to users *and* software developers. The only reason open source is useful is because of the rights afforded to users. Inclusion of the anti-commons clause makes these rights meaningless, for example:

- Can I reuse any of this code elsewhere? Does it also inherit the Anti-Commons Clause? Does that then apply to the software I imported it into, meaning I can't sell my own software?
- Can I fork this project? Does the fork also inherit the Anti-Commons Clause? How much of the code do I need to change before it stops applying? If I rewrite 100% of the code, am I still unable to sell it?

This choice of license also spits in the face of people who might contribute to your project. I'd ask myself: am I able to make money from my contributions to your project, or is that a right exclusively held by you? So you're profiting from my work and forbiding me from doing the same?

If you must write proprietary software, then you should do so. But attaching the Anti-Commons Clause to an open source license is disingenuous. It removes all of the protections of the open source license while keeping the name around for marketing value, a value which your non-free project has not earned.

Thank you for writing and publishing cool software! Please do not make the mistake of unraveling all of your hard work with a poor choice of license.

**Comment by mpdehaan** [comment]
I've written a bit on this project in the past, but ultimately this license was my choice.

You can see some of my earlier comments on it here:

https://medium.com/@michaeldehaan/going-with-the-commons-clause-1bdab4c15e5d

Also our partner program and is discussed here:

http://docs.vespene.io/partnership.html

I think a lot of people know me by my prior work and this keeps me from doing open core and keeps me from getting streamrollered by some large fish, while not forcing me down open-source adjacent lines of business.

That's ok.

You're also ok to not use it.

**Comment by carlwgeorge** [comment]
I am not a lawyer, but your Medium post and the license seem to conflict with each other.

> [First off, this is not a “no-commercial use” restriction. It does mean that you can use it completely free in your place of business, and I suspect that to be most of the audience. I want this to be used in tons of businesses!](https://medium.com/@michaeldehaan/going-with-the-commons-clause-1bdab4c15e5d#ca08)

> [For purposes of the foregoing, “Sell” means practicing any or all of the rights granted to you under the License to provide to third parties, for a fee or other consideration (including without limitation fees for hosting or consulting/ support services related to the Software), **a product or service whose value derives, entirely or substantially, from the functionality of the Software**.](https://github.com/vespene-io/vespene/blob/master/LICENSE.md#commons-clause-license-condition)

I read the entire Medium post, and I do empathize with your intentions.  But the reality is that your choice of Common Clause will hamper the adoption of Vespene.

- some users won't use it for ideological reasons
- some users won't use it due to license concerns
- since it can't be packaged in distributions, it will be less widely available

Thank you for creating this software.  Please reconsider your license choice.

**Comment by carlwgeorge** [comment]
Every single comment in this thread that was deleted was on topic and respectful.  Why would you delete them?

**Comment by SirCmpwn** [comment]
If you weren't aware, everyone can read the original text of my comment even after your attempts at censorship.

**Comment by Tyil** [comment]
Why would you censor someone, when they're just asking you to update the license in the most friendly way possible? @SirCmpwn clearly explained what's wrong with it and how it negatively impacts both users and contributors. Trying to hide the conversation and then locking it seems very immature. And as @SirCmpwn says, everyone can still read the original issue that was reported.

**Comment by carlwgeorge** [comment]
@mpdehaan Can we start a thread for this on https://talk.vespene.io or will that get deleted too?  I'm asking seriously, not trying to stoke the flames here.
