### ISSUE TITLE
Ubuntu setup requires libssl-dev

### ISSUE THREAD

**Issue by VacuousCoder** [vespene-io/vespene#24]
In 1_prepare.sh you call pip install -r ./requirements.txt. 

This tries to build cryptography which won't build without libssl-dev installed on Ubuntu. Installing libssl-dev and rerunning 1_prepare.sh fixes the issue.

**Comment by mpdehaan** [comment]
Hmm, interesting.  I didn't hit this problem but have no problem adding it to the list of packages.

Just for my curiosity, What Ubuntu version are you on?

**Comment by VacuousCoder** [comment]
16.04 server, also checked an 18.04 server box and it's not there by default either.

**Comment by Geethree** [comment]
Agreed. I am getting vespene built in a docker image based off of `ubuntu:xenial` and ran into the same issue while building the cryptography package

**Comment by mpdehaan** [comment]
Closing this since it's merged, thanks!
