### ISSUE TITLE
Enable "Login via GitHub" @ talk.vespene.io

### ISSUE THREAD

**Issue by webknjaz** [vespene-io/vespene#27]
This'd be useful

**Comment by mpdehaan** [comment]
Should be good to go, thanks for the suggestion!

**Comment by sm4rk0** [comment]
@mpdehaan, while we are here (login/signup), there's a typo (extra Unicode double quotes) in Terms of Service link when registering at talk.vespene.io:
`<a href="”/tos″" target="”_blank”">here</a>`

**Comment by mpdehaan** [comment]
Hey I normally don't get notifications on closed topics... sorry for missing this.

Honestly, I don't know where that is to be configured but I'll take a look real quick.  Discourse is a beast!
