### ISSUE TITLE
Docker images and docker-compose

### ISSUE THREAD

**Issue by Geethree** [vespene-io/vespene#34]
This would greatly simplify the install process. Especially just running `docker-compose up -d` and bootstraping a `postgres` container.

I have a fork that is currently being worked on, but am currently running into difficulties around the current install process. Namely, sudo and database. Nothing insurmountable, just the first roadblock of a naive attempt

Any preference as to which base image python3, debian, xenial, alpine?

**Comment by mpdehaan** [comment]
Hi @Geethree, 

I'd totally like to offer this as an option up to folks - there's currently a thread to discuss this over https://talk.vespene.io/t/ability-to-contanerize-the-components-of-vespene/30/13 .. would you like to join in?

Thanks!

**Comment by btotharye** [comment]
Currently PR #39 is trying to address this

**Comment by pyToshka** [comment]
@Geethree you can try my [example](https://github.com/pyToshka/vespene-docker)

**Comment by mpdehaan** [comment]
Per conversation on the forum I think we should let this evolve out of tree.  Absolutely and completely welcome forum discussion and as a solution evolves we could maybe merge something back in later.
