### ISSUE TITLE
make gunicorn bind options configurable in 0_common.sh

### ISSUE THREAD

**Issue by mpdehaan** [vespene-io/vespene#37]
To make it easy for people to set up the application, I've added by suggestion the "--bind 0.0.0.0:8000" option to supervisor's configuration for now.

This setting is good for people who are trying it out for the first time, but not ideal for those who want to proxy the service with NGINX or Apache, which should be the additional production run - they would need to know to edit the supervisor configuration.

To fix this, we can either mention this in the docs in the security guide or add a new option for bind options in 0_common.sh, which would also make it super easy to reassign the port.

I think I like that last option better.

**Comment by chopraaa** [comment]
I think the setup instructions should be divided into 2 parts - quick setup and recommended practices. The `./vespene/build` scripts should be the recommended way to deploy Vespene for testing and the documentation should refer to the scripts for getting started. In addition to these scripts, we can refer to some sketchy docker images consisting of only django and postgresql for quick deployment.

The second part should cover best practices, with notes like - use nginx as a reverse proxy, and so on. We can also have separate dockerfiles as per our recommendations for production systems. This way we can demonstrate how to use nginx, postgresql, and vespene's containers for production setups.

**Comment by mpdehaan** [comment]
Any sort of best practices stuff is going to be left for the docs site for the short term.

Because things like especially Apache diverge rapidly between Ubuntu and CentOS (and with versions) that would be too much for me to support.

It's also pretty easy for someone writing their own install automation (ansible, puppet, chef, docker, etc) to add on top if they want.

The demo scripts are going to set it up in a production grade and stable configuration, just with the exception that you really should be proxying it.

Bind options are going to come with a warning (because of https://), basically.

**Comment by mpdehaan** [comment]
This is now part of 0_common.sh.  It defaults to localhost for security reasons and I'll call it out in a bit more detail in the docs.
