### ISSUE TITLE
Prepare Error

### ISSUE THREAD

**Issue by btotharye** [vespene-io/vespene#5]
My Setup:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

When running sudo bash 1_prepare.sh I am seeing the below after fixing the wrong repository piece in the file.

I'm debugging now but thought I'd put this here for tracking.

```
Installing python packages...
/usr/bin/pip3 install -r ../../requirements.txt --trusted-host pypi.org --trusted-host files.pypi.org --trusted-host files.pythonhosted.org
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

**Comment by btotharye** [comment]
It is related to the pip location for python3.6 I have a easier way I'm pushing up a PR to fix this now.

**Comment by mpdehaan** [comment]
Thanks for the PR!
