### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [vespene-io/vespene#55]
They are all free for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

**Comment by mpdehaan** [comment]
Ha, I have no plan of marketing for another build system :)

Meanwhile, automated testing may occur, but the time for that is not now.  Probably when I get a chance to weld the REST API back in, there could be some functional tests.

People will be able to run them easily from makefiles, as they can already do now with some targets like pyflakes.

But ultimately a distributed system that has a lot of side effects is going to get a lot of mock testing which has rapidly diminishing returns.

I expect contribution to be pretty active, but not nearly as active as ansible (so many modules all changing at once) so I'm not really worried about it.

Appreciate your for stopping by with the suggestion but I hope you understand the reasoning for it.

(Finally, as shared in issue_template.md, we're not using the issue queue for RFE tickets to keep this queue organized - which was a HUGE problem with past projects - check out talk.vespene.io if you haven't already)

Thanks!
