### ISSUE TITLE
Output and Messages text areas are not selectable in Build -> Output tab

### ISSUE THREAD

**Issue by sm4rk0** [vespene-io/vespene#69]
Mentioned text areas are not selectable making it hard to copy-paste the build logs. Discussed [here](https://talk.vespene.io/t/make-output-and-messages-textareas-selectable-in-build-output-tab/39/2).

Workaround: use Developer tools (right-click the text area -> Inspect element) and double-click the text area's value.

**Comment by mpdehaan** [comment]
Thanks this should be an easy fix in forms.py - I’ll see if there is an easy way to do selectable but still not editable and worst case we can just make it editable as there is no way to save it anyway. Will probably get to this Sunday or Monday, apologies on not noticing something obvious.
