### ISSUE TITLE
Have database.py updated on bash run

### ISSUE THREAD

**Issue by btotharye** [vespene-io/vespene#8]
Anytime the bash 1_prepare.sh runs and sources the 0_common.sh it should also update the database.py file in the /etc/vespene/settings.d/database.py file.

**Comment by btotharye** [comment]
If you can tell me where this logic is I can update it but just putting this here for documentation sake since it doesn't appear to update it correctly atm.

Thanks

**Comment by mpdehaan** [comment]
Hey @btotharye - the database.py setup is actually done in 3_application.sh.

Let me know if that answers the question, or if not, maybe can you clarify what kind of problem you are seeing?

**Comment by btotharye** [comment]
The issue is if I update the person in the 0 file and re-run it always had a database pw problem cause the env variable wasn’t updated in the database.py file I’ll double check again

**Comment by mpdehaan** [comment]
I don't understand how that would be possible.  Let us know!

**Comment by btotharye** [comment]
Gonna close for now will rebuild all this and will reopen if it still happens
